# Site settings
title: Graphics
email: dnvy0084@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  컴퓨터 그래픽스, 개발 및 수학 관련 블로그 포스팅입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dnvy0084.github.io/" # the base hostname & protocol for your site
twitter_username: dnvy0084
github_username:  dnvy0084

# Build settings
markdown: redcarpet
